* *********** OPTOGENETICS NOTES *********** *
* 2013nov25 Meeting with Dan and Werapong
- Data format:
>> load basicOpto.flatStruct2.mat
>> trials
trials = 
1x27 struct array with fields:
    desc
    subject <- name of monkey
    protocolVersion
    timeStartWallclock
    TrialStart <- always 0
    trialIdStr
    protocol
    TrialEnd
    duration
    trialId
    cellNumber <- interesting just for data management
    saveTag
    paddingPre <- how much time recorded on either side of stimulation
    paddingPost
    stimPulseWidth <- duration in microseconds (not ms)
    stimPulseFreq <- frequency of stimulation
    stimDuration <- useful in continuous cases (not in this dataset)
    stimLaserColor <- usually green
    Stim <- timestamps relative to start/stop of trial in ms of stimulus; for pulse trains, from start of 1st pulse to end of last pulse
    StimEnd
    StimPulse
    StimPulseEnd
    unit97_1
    unit97_2
    unit99_1
    unit99_2
    unit99_255
- Spikes are in unitX_Y where X is electrode and Y is channel
- Channel 97 is optrode (almost always)
* 2013dec11 Meeting with Dan
** Data
- 49x1 structure: each entry is a recording block, 30-40 trials, sitting there, we're stimulating
- Passive stimulation, channel 97, all Olaf so as to compare PMd and M1
- Updated plotdandata.m to read new data structure
- Nurmikko estimated light spread out of optrode -- have Monte Carlo simulation of full shape of light coming out; could start with 1 mm radius sphere
- Optotrode is probably sitting just above L5 most of the time (see Ilka 2011 paper)
- Need to put magnitude on photocurrent -- can use light power density
- Virus preferentially infects cells in deeper layers (i.e. L5/6)
- Quality metric -- 1 or 2 is single-unit, 3 or 4 is MUA, >4 is crappy
  = Not included in sent data but Dan will send
** Questions
*** What are the main differences between M1 and PMd data?
- Not a sharp distinction between the two -- at border get Betz cells in what otherwise looks like PMd
- No difference in light response, but see more preparatory activity in PMd and more preparatory activity in M1
- Higher electrical stimulation thresholds to evoke movement as move more anterior
- Also true as you go further into sulcus of M1 -- these recordings are rostral; optogen stimulation is definitely in rostral part
*** Value-add from modeling?
- Have already looked at spatiotemporal dynamics
- Can try to get spatial spread from model to match spatial spread in data, convincing if don't have to derive any parameters -- if light spread and motor cortex connectivity predict response
- If can get good model of basic light response working, in mouse world people think of opsins as having maximum rate (see Joanna's paper, emailed). See percentage of spikes evoked by frequency. CHR2 doesn't drive spiking above 50 Hz because opsin is too slow. Made faster mutants that open and close faster. If want to reliably drive spiking at higher rate, would need faster opsin. But this is specific to mouse -- can drive spiking very fast in M1 neurons. Maybe because some neurons spike fast to begin with? Up to 150 Hz naturally -- rare but do occur as single units. At single-unit level, how can we drive spiking that fast? Range of firing rates have been characterized before -- to see firing rates 20-80 Hz range not uncommon. But when stimulate, see very high firing. Where do the models saturate with firing? If dump continuous light on cell, does it hit the same range of firing rates as we observe? Does it track 80 Hz as well as experimental cells? Usually just use 200 ms pulse because biggest changes in firing. Is this because cell is intrinsically capable of spiking that fast, or is it because hitting a glob of cells, so are there synaptic currents playing a big role as well? One thing we can't do in the real data is reliably know which cells have opsin and which don't. Can look at latency to first spike, but haven't looked at that distribution (e.g. what's the latency to the 1st spike, and is it bimodal, i.e. directly and indirectly stimulated). In a cell that you know is non-expressing, how fast is that cell driven vs. a directly expressing cell. If shut off synaptic input to a cell that is expressing, does it make a big difference to the firing rate? Would also like to separate excitatory from inhibitory -- narrow-spiking vs. wide-spiking. Evidence suggests that I cells have narrow waveforms, E are wide. If interesting difference in firing patterns between E and I cells in model, would be interesting to look for that in the data.
- Also interesting to know re: spatial connectivity -- in M1 quite local, <1 mm, would be interesting to know how spatial spread of changes in firing rates, which in data are within 2 mm of optrode, which is roughly size of light ball, but don't know how much light power you need to drive spiking in monkey neurons. Here's the spatial spread in model, agrees with spatial spread in data, here's spatial spread of firing rate changes vs. spatial spread of direct stimulation, to show that you (maybe) get further due to synaptic connections (or maybe inhibitory shutdown, peripheral inhibition?). Don't know much about how opsin maps on to actual circuit; how it maps onto different layers or cell types. Lowest-hanging fruit would be to use data to get reasonable model of light's effect on circuit, then can ask a lot in the model that can't ask in the data. Can provide stats to match model to data, can then go further with model.
- Downstream questions with task -- talk later.
- Joanna Mattis' paper uses a lot of different metrics -- can apply to model
  = In mouse slice, but kinetics similar in macaque
  = Uses exact same opsin -- C1V1_T
  = Idea that they don't track at higher frequencies -- Fig. 2A
* 2013dec12 Meeting with UCSF
** Call with Salva
- Using muscle lengths and joint angles to feed into RBM
- RBM output feeds into proprioceptive layer
- Translation between joint angles and muscle lengths not easy
- Currently using muscle lengths; used to use joint angles
- Should be both more realistic and better result
- Idea of using Joe's model to replicate Maria's experiments
- In simple for visual input will be a perfect signal so might need to add some noise so that the proprioceptive signal can be used too
** Meeting with Joe
- Talked about stuff.
* 2014jan08 Planning NCM abstract
** Email to Dan et al.
Hey guys,

FYI, I'm planning on throwing together something quickly for the Neural Control of Movement conference:
http://www.ncm-society.org/default.aspx?PageID=1010

The abstract deadline (for talks) is this Friday (eek!), so I'll try to send a draft abstract tomorrow (Thursday) night. For author order I was thinking me, Dan, Werapong, Salva, Krishna, Bill -- does that sound OK? If not let me know what you suggest, e.g. if you guys should be in the reverse order.

The working title I'm thinking of is "Information flow in optogenetically stimulated macaque primary motor cortex: simulation and experiment", for the "Theoretical and Computational Motor Control" theme. The plan is to (1) introduce a model of macaque M1 based experimental connectivity data, (2) calibrate that model (including an opsin model) to your data, (3) show in the model how optogenetic stimulation affects information flow between cortical layers (something that can't readily be measured experimentally). If you have any other suggestions, please let me know!

C 
* 2014jan09 Woring on NCM abstract
- Registered for NCM, started on abstract in submission manager.
- See /u/cliffk/talks/2014ncm
** Plan
- +07:00-08:00 06:50-08:23 1:00 1:33 Incorporate M1 connectivity in model+
- +08:00-09:00 08:23-08:24 1:00 0:01 Make sure model has vaguely realistic firing rates etc.+
- +10:30-11:30 09:44-10:47 1:00 1:03 Check that opsin stimulation works+
- +11:30-12:00 10:50-11:27 0:30 0:37 Decide on which experimental dataset to use+
- +12:00-01:00 12:07-4:06 1:00 3:59 Analyze it in terms of firing rate and mutual information+
- +01:00-01:30 04:06-04:24 0:30 0:18 Read opsin paper+
- +01:30-02:30 04:24-04:55 1:00 0:31 Tune single-cell opsin model to match experimental results+
- 02:30-03:30 05:07-# 1:00 Tune opsin-stimulated network model to match experimental results
- 03:30-04:00 0:30 Calculate Granger causality between layers
- 04:00-05:00 1:00 Write abstract
Total: 8:30
** Incorporating M1 connectivity in model
- Only things that need to change are connectivity and cell types
- Fairly straightforward; used the in-column connectivity (i.e. [0] instead of [1] or [2]) from Ash's model
** Realistic firing rates
- Thankfully it did, first go. Firing rate was 1.6 Hz, which was a bit low, but can be tuned later.
** Opsin channel
- Had to recompile, but otherwise it works -- acts just like an AMPA channel, which is not surprising, because that's how it's written.
** Experimental dataset
- Obvious file to use is monkeyO_BasicOptoForREPAIR.mat
- Third block (used in last quarterly) looks good, or could use all...
  = Well not all, 1-13 are M1, and 45-49:
>> for i=1:49, disp([i tmp.data(i).channelLocationInfo(1).isM1]), end
- Tried to concatenate all blocks, but hard because of different units
** Experimental analysis
- Hmm. After many hours of futzing around, decided just to go with the results in the quarterly report... :/
- Not enough cells to calculate mutual information reliably.
** Opsin paper
- They're using C1V1TT (see Dan's email 2013-11-26).
- Here's the paper: Mattis J, Tye KM, Ferenczi EA, Ramakrishnan C, O'Shea DJ, Prakash R, Gunaydin LA, Hyun M, Fenno LE, Gradinaru V, Yizhar O, Deisseroth K. Principles for applying optogenetic tools derived from direct comparative analysis of microbial opsins. Nat Methods. 2011 Dec 18;9(2):159-72.
- ./articles/mattis11_optogenetics.pdf
  = Channel has a tau_off of about 50 ms (Fig. 1H)
  = Spike reliability is close to 100% with slow stimulation, drops off sigmoidally to near 0% at 100 Hz...basically saying that they evoke a maximum firing rate of 5-10 Hz or so
** Tuning network model
- Want baseline firing rate of ~10 Hz, going up to ~60 with "constant" stimulation for 200 ms and then undershooting to 5; 20, 40, and 80 Hz stimulation all bring it up to 20 Hz for 1 s and then back to baseline.
- OK, got baseline firing rate...but, play() code doesn't seem to be working
- Getting nans in the LFP... :(
*** NaNs problem
- Hmm, when I plot the raw voltage traces, they look fine...
* 2014jan20 Meeting with Werapong
** Quantifying firing rates
- Hmm when I reran with slightly different parameters, it's a little on the low side -- 3.5 Hz without optogenetics, 7 Hz with
- OK that's better -- 8 Hz without opto, 23 Hz with
** Ideas for paper
- Distilled from  meeting with Dan on 2013dec11
- Can try to get spatial spread from model to match spatial spread in data, convincing if don't have to derive any parameters -- if light spread and motor cortex connectivity predict response
- If can get good model of basic light response working, in mouse world people think of opsins as having maximum rate (see Joanna's paper, emailed). See percentage of spikes evoked by frequency; at single-unit level, how can we drive spiking up to 150 Hz?
- Range of firing rates have been characterized before -- to see firing rates 20-80 Hz range not uncommon. But when stimulate, see very high firing. Where do the models saturate with firing? 
- One thing we can't do in the real data is reliably know which cells have opsin and which don't, how fast is spiking in expressing vs. non-expressing cells?
- If shut off synaptic input to a cell that is expressing, does it make a big difference to the firing rate? 
  = WG: interesting question
- If interesting difference in firing patterns between E and I cells in model, would be interesting to look for that in the data.
- Compare spatial spread of light with spatial spread of activation -- e.g. effect of connections
** Meeting
- Agree to aim for not completely trivial paper but not all-out, e.g. J Neurosci or similar
- Functionality of opsins could depend on area of injection -- in Joanna's paper injected in hippocampus, not motor cortex
- Kinematics can change depending on where you inject -- can't compare e.g. rat hippocampus to macaque M1
- Question: why can some neurons spike very fast (locked to stimulus pulses) even though kinematics of opsin are slow? Can't tell whether this is due to indirect network effects
  = Some neurons show spiking >100 Hz with continuous light pulses
- Latency to first spike: Karl says can't tell whether a response is direct or indirect (from experiments in slices)
- In Histed et al. (2009), shows that ICMS is enough to make neurons to spike without synaptic input -- same with optogenetics?
- Lehman group had a poster at SfN saying that inhibitory neurons can have broad waveform or excitatory can have narrow -- so can't use as a consistent rule
- Idea: compare optogenetic spatial spread with microstim; MiSt can evoke movement but optogenetics can't
  = Histed et al. shows spatial extent of microstimulation, Shenoy has that as well
  = Can't say that a given microstim current = given optical power. Can use model to compare?
    = CK: probably not since would need detailed single-cell model
- "If could suddenly record from 1000s of neurons, what would you use it for?"
  = Spatiotemporal dynamics -- do they change when give the network a task?
    = Not in this paper, but could look at how spatiotemporal dynamics change with a task
    = Spatiotemporal dynamics = PCA components probably the main one, plus Fano factor, PSTH, etc. -- PCA to get a qualitative overview
- Interesting question: is spatial extent of ball of activation increased or decreased as a result of network effects? e.g. if you turn off synaptic connections, how does that change the activity pattern?
* 2014feb20 CNS abstract
** Plan
- +04:00-04:30 05:30-07:17 0:30 1:47 Verify that baseline firing rate is OK+
- 04:30-05:30 1:00 Verify that opsin response is OK
- 05:30-07:30 2:00 Put in spatially-dependent stimulation
- 08:30-10:30 2:00 Calculate firing rate response profile (and hope to hell it matches experiment!)
- 10:30-11:30 1:00 Calculate single-cell firing responses for stimulated vs. non-stimulated
- 11:30-01:30 2:00 Take out lateral connections and see how response changes in single cells and across network
- 01:30-02:30 1:00 Verify that Granger results still hold
- 02:30-03:30 1:00 Write abstract
** Merging
- First step is to merge with microstim model, which has several bug fixes...
[commit 25]
** Baseline firing rate
- Using microstim simulation parameters yields reasonable-ish firing rates:
  = ck/01-mistparams.sim
  = ck/01-mistparams-raster.png
- Tuning weights and such:
  = ck/01-mistparams2.sim
  = ck/01-mistparams2-raster.png
  = ck/01-mistparams2-movie.png
  = Looks pretty good...
[commit 26]
** Opsin response
- Changed stimulus region to just the center part...
- Using 50% of cells infected; arbitrary, but want to look at difference between stimulated vs. not...
- Just the opsin response produces traveling waves:
  = ck/01-mistparams3.sim
  = ck/01-mistparams3-movie.png
- Trying with more inhibition:
  = ck/01-mistparams4.sim
  = ck/01-mistparams4-movie.png
  = OK, that shut everything down.
[commit 28]
* 2014feb21 CNS abstract cont.
- OK, so yesterday didn't quite go according to plan.
** Plan
- 11:30-12:30 1:00 Get single-cell opsin response up to 300 Hz
- 01:30-02:30 1:00 Verify that baseline firing rate is OK
- 02:30-03:30 1:00 Put in spatially-dependent stimulation
- 03:30-04:30 1:00 Calculate firing rate response profile (and hope to hell it matches experiment!)
- 04:30-05:00 0:30 Calculate single-cell firing responses for stimulated vs. non-stimulated
- 05:00-06:00 1:00 Take out lateral connections and see how response changes in single cells and across network
- 06:00-06:30 0:30 Verify that Granger results still hold
- 06:30-07:30 1:00 Write abstract
[commit 29]
** Single-cell opsin response
- OK, got it up to 195 Hz:
  = ck/02-opsintest.png
  = So should be able to do the same in the model!
[commit 30]
** Firing rates
- Optogenetic stimulation finally seems to be working!
  = ck/02-optostimtest.sim
  = ck/02-optostimtest-movie.png
- Had to fix the stimulus code, it was kind of crappy.
[commit 33]
- Trying enormous sims -- they're still quite fast! Here's a scale=32 sim (24800 cells):
  = ck/02-opostimtest2-movie.png
  = ck/02-optostimtest2.sim
  = 119 s total. Not bad. Not bad at all.
[commit 34]
- OK, this looks reasonable to me:
  = ck/02-optostimtest3.sim
  = ck/02-optostimtest3-raster.png
  = ck/02-optostimtest3-movie.png
- Yeah, OK, I guess this is ok. Moving on to spatial properties.
[commit 35]
** Spatially-dependent input
- Hmm, looks like I broke the cells:
  = ck/02-optostimtest5-movie.png
- Can't easily replicate it in opsintest.py -- must be activating each other
- OK, fixed, just put a ceiling on the weight.
- Made a video, and it's cool!
  = https://docs.google.com/file/d/0BwYtCYG9J4v7QTBaXzk3OWZzWlk/edit
  = ck/02-optostimtest6-raster.png
[commit 36]
- Yep, looks good with background activity too:
  = ck/02-optostimtest7-raster.png
- Made the simmovie.py code show past activity too, which is cool.
[commit 37]
** Calculating firing response profile
- Should be fairly straightforward...
- Yep, it is! Need to turn down the intensity a bit:
  = ck/03-distanceprofile1.png
  = cf. ck/03-exp-distanceprofile.pdf
[commit 38]
- Now I need to tune. OK, so reduce percentage by a factor of 2 (from 0.8 to 0.4), reduce weight by a factor of 2 (from 100 to 50), that should do it...
- Nope, it didn't. Reducing to 5...
- Now needs to be a little higher, setting to 10...
- Whoa!! Looks great!
  = ck/03-distanceprofile2.png
  = Even has a slight fall-off very close to the stimulus.
  = Peak of profile is a little too close to optrode, though.
  = Still, OMG I am happy.
[commit 39]
- Moving good file to ./data/opto-with-conns.mat.
** Removing lateral connections
- Not as exciting, but about as expected:
  = ck/03-distanceprofile2-no-conns.png
- Trying to plot everything on one graph:
  = ck/03-distanceprofiles.png
- OK, so I have everything I need to write the abstract! Boo-goddang-yah.
** Writing abstract
- See /u/cliffk/posters/2014cns/cns2014-abstract-kerr.doc
* TODO
- +11:30-12:30 11:30-11:50 1:00 0:20 Get single-cell opsin response up to 300 Hz+
- +01:30-02:30 01:00-04:00 1:00 3:00 Verify that firing rates are OK+
- +02:30-03:30 04:00-04:47 1:00 0:47 Put in spatially-dependent stimulation+
- +03:30-04:30 04:47-06:02 1:00 1:15 Calculate firing rate response profile (and hope to hell it matches experiment!)+
- +04:30-05:00 0:30 Calculate single-cell firing responses for stimulated vs. non-stimulated+
- +05:00-06:00 1:00 Take out lateral connections and see how response changes in single cells and across network+
- +06:00-06:30 0:30 Verify that Granger results still hold+
- 06:30-07:30 1:00 Write abstract
7:00 total
