#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _A_reg(void);
extern void _AMPA_reg(void);
extern void _GABAa_reg(void);
extern void _MyExp2SynBB_reg(void);
extern void _MyExp2SynNMDABB_reg(void);
extern void _NMDA_reg(void);
extern void _Nca_reg(void);
extern void _OFThpo_reg(void);
extern void _OFThresh_reg(void);
extern void _ar_reg(void);
extern void _cad_reg(void);
extern void _cadad_reg(void);
extern void _cal_reg(void);
extern void _cat_reg(void);
extern void _expsynstdp_reg(void);
extern void _iholmw_reg(void);
extern void _izhi2003a_reg(void);
extern void _izhi2003b_reg(void);
extern void _izhi2007a_reg(void);
extern void _izhi2007b_reg(void);
extern void _k2_reg(void);
extern void _ka_reg(void);
extern void _kacurrent_reg(void);
extern void _kahp_reg(void);
extern void _kc_reg(void);
extern void _kca_reg(void);
extern void _kdr_reg(void);
extern void _kdrcurrent_reg(void);
extern void _km_reg(void);
extern void _km2_reg(void);
extern void _kv_reg(void);
extern void _nacurrent_reg(void);
extern void _naf_reg(void);
extern void _nap_reg(void);
extern void _naz_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," mod/A.mod");
    fprintf(stderr," mod/AMPA.mod");
    fprintf(stderr," mod/GABAa.mod");
    fprintf(stderr," mod/MyExp2SynBB.mod");
    fprintf(stderr," mod/MyExp2SynNMDABB.mod");
    fprintf(stderr," mod/NMDA.mod");
    fprintf(stderr," mod/Nca.mod");
    fprintf(stderr," mod/OFThpo.mod");
    fprintf(stderr," mod/OFThresh.mod");
    fprintf(stderr," mod/ar.mod");
    fprintf(stderr," mod/cad.mod");
    fprintf(stderr," mod/cadad.mod");
    fprintf(stderr," mod/cal.mod");
    fprintf(stderr," mod/cat.mod");
    fprintf(stderr," mod/expsynstdp.mod");
    fprintf(stderr," mod/iholmw.mod");
    fprintf(stderr," mod/izhi2003a.mod");
    fprintf(stderr," mod/izhi2003b.mod");
    fprintf(stderr," mod/izhi2007a.mod");
    fprintf(stderr," mod/izhi2007b.mod");
    fprintf(stderr," mod/k2.mod");
    fprintf(stderr," mod/ka.mod");
    fprintf(stderr," mod/kacurrent.mod");
    fprintf(stderr," mod/kahp.mod");
    fprintf(stderr," mod/kc.mod");
    fprintf(stderr," mod/kca.mod");
    fprintf(stderr," mod/kdr.mod");
    fprintf(stderr," mod/kdrcurrent.mod");
    fprintf(stderr," mod/km.mod");
    fprintf(stderr," mod/km2.mod");
    fprintf(stderr," mod/kv.mod");
    fprintf(stderr," mod/nacurrent.mod");
    fprintf(stderr," mod/naf.mod");
    fprintf(stderr," mod/nap.mod");
    fprintf(stderr," mod/naz.mod");
    fprintf(stderr, "\n");
  }
  _A_reg();
  _AMPA_reg();
  _GABAa_reg();
  _MyExp2SynBB_reg();
  _MyExp2SynNMDABB_reg();
  _NMDA_reg();
  _Nca_reg();
  _OFThpo_reg();
  _OFThresh_reg();
  _ar_reg();
  _cad_reg();
  _cadad_reg();
  _cal_reg();
  _cat_reg();
  _expsynstdp_reg();
  _iholmw_reg();
  _izhi2003a_reg();
  _izhi2003b_reg();
  _izhi2007a_reg();
  _izhi2007b_reg();
  _k2_reg();
  _ka_reg();
  _kacurrent_reg();
  _kahp_reg();
  _kc_reg();
  _kca_reg();
  _kdr_reg();
  _kdrcurrent_reg();
  _km_reg();
  _km2_reg();
  _kv_reg();
  _nacurrent_reg();
  _naf_reg();
  _nap_reg();
  _naz_reg();
}
